import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';

interface Transaction {

            id:string,
            date: string,
            amount:number,
            category: string,
            type: 'income' | 'expense',
            description: string,
            account: string,
            icon:string
}

interface TransactionState {
  transactions: Transaction[];
  setTransactions: (data: Transaction[]) => void;
  addTransaction: (tx: Transaction) => void;
  clearTransactions: () => void;
  deleteTransaction: (id: string) => void;
  editTransaction: (id: string, updatedData: Partial<Transaction>) => void;
}

export const useTransactionStore = create<TransactionState>()(
  persist(
    (set) => ({
      transactions: [

          {
            id: 'txn-001',
            date: '2026-04-01',
            amount: 125000,
            category: 'Salary',
            type: 'income',
            description: 'April Salary — Tata Consultancy Services',
            account: 'HDFC Savings',
            icon: 'briefcase',
          },
          {
            id: 'INV_0040',
            date: '2026-04-01',
            amount: 8500,
            category: 'Salary',
            type: 'income',
            description: 'Monthly Salary',
            account: 'Main Account',
            icon: 'wallet',
          },
          {
            id: 'INV_0039',
            date: '2026-04-02',
            amount: 52.99,
            category: 'Entertainment',
            type: 'expense',
            description: 'Adobe Creative Cloud',
            account: 'Main Account',
            icon: 'palette',
          },
          {
            id: 'INV_0038',
            date: '2026-04-03',
            amount: 120.5,
            category: 'Shopping',
            type: 'expense',
            description: 'Amazon Purchase',
            account: 'Main Account',
            icon: 'package',
          },
          {
            id: 'INV_0037',
            date: '2026-04-05',
            amount: 2200,
            category: 'Freelance',
            type: 'income',
            description: 'Freelance Project',
            account: 'Main Account',
            icon: 'laptop',
          },
          {
            id: 'INV_0036',
            date: '2026-04-07',
            amount: 145.0,
            category: 'Utilities',
            type: 'expense',
            description: 'Electricity Bill',
            account: 'Main Account',
            icon: 'zap',
          },
          {
            id: 'INV_0035',
            date: '2026-04-08',
            amount: 60.0,
            category: 'Healthcare',
            type: 'expense',
            description: 'Gym Membership',
            account: 'Main Account',
            icon: 'activity',
          },
          {
            id: 'INV_0034',
            date: '2026-04-10',
            amount: 6.5,
            category: 'Food & Dining',
            type: 'expense',
            description: 'Starbucks Coffee',
            account: 'Main Account',
            icon: 'coffee',
          },
          {
            id: 'INV_0033',
            date: '2026-04-12',
            amount: 24.0,
            category: 'Transport',
            type: 'expense',
            description: 'Uber Ride',
            account: 'Main Account',
            icon: 'car',
          },
          {
            id: 'INV_0032',
            date: '2026-04-14',
            amount: 450.0,
            category: 'Investment Returns',
            type: 'income',
            description: 'Stock Dividends',
            account: 'Main Account',
            icon: 'trending-up',
          },
          {
            id: 'INV_0031',
            date: '2026-04-15',
            amount: 19.99,
            category: 'Entertainment',
            type: 'expense',
            description: 'Netflix Subscription',
            account: 'Main Account',
            icon: 'film',
          },
          {
            id: 'INV_0030',
            date: '2026-03-01',
            amount: 8500,
            category: 'Salary',
            type: 'income',
            description: 'Monthly Salary',
            account: 'Main Account',
            icon: 'wallet',
          },
          {
            id: 'INV_0029',
            date: '2026-03-02',
            amount: 2400,
            category: 'Housing',
            type: 'expense',
            description: 'House Rent',
            account: 'Main Account',
            icon: 'home',
          },
          {
            id: 'INV_0028',
            date: '2026-03-05',
            amount: 350.2,
            category: 'Groceries',
            type: 'expense',
            description: 'Grocery Store',
            account: 'Main Account',
            icon: 'shopping-cart',
          },
          {
            id: 'INV_0027',
            date: '2026-03-07',
            amount: 10.99,
            category: 'Entertainment',
            type: 'expense',
            description: 'Apple Music',
            account: 'Main Account',
            icon: 'music',
          },
          {
            id: 'INV_0026',
            date: '2026-03-10',
            amount: 1500,
            category: 'Freelance',
            type: 'income',
            description: 'Freelance Design',
            account: 'Main Account',
            icon: 'palette',
          },
          {
            id: 'INV_0025',
            date: '2026-03-12',
            amount: 80.0,
            category: 'Utilities',
            type: 'expense',
            description: 'Internet Bill',
            account: 'Main Account',
            icon: 'globe',
          },
          {
            id: 'INV_0024',
            date: '2026-03-15',
            amount: 120.0,
            category: 'Food & Dining',
            type: 'expense',
            description: 'Restaurant Dinner',
            account: 'Main Account',
            icon: 'utensils',
          },
          {
            id: 'INV_0023',
            date: '2026-03-18',
            amount: 65.0,
            category: 'Transport',
            type: 'expense',
            description: 'Gas Station',
            account: 'Main Account',
            icon: 'fuel',
          },
          {
            id: 'INV_0022',
            date: '2026-03-20',
            amount: 2000,
            category: 'Salary',
            type: 'income',
            description: 'Bonus Payment',
            account: 'Main Account',
            icon: 'sparkles',
          },
          {
            id: 'INV_0021',
            date: '2026-03-25',
            amount: 299.0,
            category: 'Shopping',
            type: 'expense',
            description: 'Software License',
            account: 'Main Account',
            icon: 'code',
          },
          {
            id: 'INV_0020',
            date: '2026-02-01',
            amount: 8500,
            category: 'Salary',
            type: 'income',
            description: 'Monthly Salary',
            account: 'Main Account',
            icon: 'wallet',
          },
          {
            id: 'INV_0019',
            date: '2026-02-04',
            amount: 1200,
            category: 'Transport',
            type: 'expense',
            description: 'Flight Ticket',
            account: 'Main Account',
            icon: 'plane',
          },
          {
            id: 'INV_0018',
            date: '2026-02-06',
            amount: 850.0,
            category: 'Housing',
            type: 'expense',
            description: 'Hotel Stay',
            account: 'Main Account',
            icon: 'building',
          },
          {
            id: 'INV_0017',
            date: '2026-02-10',
            amount: 3000,
            category: 'Freelance',
            type: 'income',
            description: 'Consulting Fee',
            account: 'Main Account',
            icon: 'users',
          },
          {
            id: 'INV_0016',
            date: '2026-02-14',
            amount: 250.0,
            category: 'Food & Dining',
            type: 'expense',
            description: 'Valentine Dinner',
            account: 'Main Account',
            icon: 'heart',
          },
          {
            id: 'INV_0015',
            date: '2026-02-18',
            amount: 499.99,
            category: 'Shopping',
            type: 'expense',
            description: 'New Monitor',
            account: 'Main Account',
            icon: 'monitor',
          },
          {
            id: 'INV_0014',
            date: '2026-02-20',
            amount: 1800,
            category: 'Investment Returns',
            type: 'income',
            description: 'Crypto Profit',
            account: 'Main Account',
            icon: 'bitcoin',
          },
          {
            id: 'INV_0013',
            date: '2026-02-22',
            amount: 200.0,
            category: 'Transport',
            type: 'expense',
            description: 'Car Insurance',
            account: 'Main Account',
            icon: 'shield',
          },
          {
            id: 'INV_0012',
            date: '2026-02-25',
            amount: 85.0,
            category: 'Healthcare',
            type: 'expense',
            description: 'Gym Supplement',
            account: 'Main Account',
            icon: 'package',
          },
          {
            id: 'INV_0011',
            date: '2026-02-28',
            amount: 100.0,
            category: 'Other',
            type: 'income',
            description: 'Gift from Friend',
            account: 'Main Account',
            icon: 'gift',
          },
          {
            id: 'INV_0010',
            date: '2026-01-01',
            amount: 8500,
            category: 'Salary',
            type: 'income',
            description: 'Monthly Salary',
            account: 'Main Account',
            icon: 'wallet',
          },
          {
            id: 'INV_0009',
            date: '2026-01-05',
            amount: 45.0,
            category: 'Utilities',
            type: 'expense',
            description: 'AWS Cloud Services',
            account: 'Main Account',
            icon: 'cloud',
          },
          {
            id: 'INV_0008',
            date: '2026-01-05',
            amount: 24.0,
            category: 'Utilities',
            type: 'expense',
            description: 'Digital Ocean',
            account: 'Main Account',
            icon: 'cloud-lightning',
          },
          {
            id: 'INV_0007',
            date: '2026-01-10',
            amount: 600.0,
            category: 'Shopping',
            type: 'income',
            description: 'Sold Old Laptop',
            account: 'Main Account',
            icon: 'laptop',
          },
          {
            id: 'INV_0006',
            date: '2026-01-12',
            amount: 59.99,
            category: 'Entertainment',
            type: 'expense',
            description: 'Steam Games',
            account: 'Main Account',
            icon: 'gamepad',
          },
          {
            id: 'INV_0005',
            date: '2026-01-15',
            amount: 50.0,
            category: 'Utilities',
            type: 'expense',
            description: 'Phone Bill',
            account: 'Main Account',
            icon: 'smartphone',
          },
          {
            id: 'INV_0004',
            date: '2026-01-20',
            amount: 50.0,
            category: 'Other',
            type: 'income',
            description: 'Referral Bonus',
            account: 'Main Account',
            icon: 'tag',
          },
          {
            id: 'INV_0003',
            date: '2026-01-22',
            amount: 35.0,
            category: 'Food & Dining',
            type: 'expense',
            description: 'Pizza Night',
            account: 'Main Account',
            icon: 'pie-chart',
          },
          {
            id: 'INV_0002',
            date: '2026-01-25',
            amount: 42.5,
            category: 'Healthcare',
            type: 'expense',
            description: 'Pharmacy',
            account: 'Main Account',
            icon: 'cross',
          },
          {
            id: 'INV_0001',
            date: '2026-01-30',
            amount: 1200,
            category: 'Investment Returns',
            type: 'income',
            description: 'Tax Refund',
            account: 'Main Account',
            icon: 'landmark',
          },

      ],

      setTransactions: (data) => set({ transactions: data }),

      addTransaction: (tx) =>
        set((state) => ({ transactions: [tx, ...state.transactions] })),

      deleteTransaction: (id) =>
        set((state) => ({
          transactions: state.transactions.filter((tx) => tx.id !== id),
        })),
      editTransaction: (id, updatedData) =>
        set((state) => ({
          transactions: state.transactions.map((tx) =>
            tx.id === id ? { ...tx, ...updatedData } : tx,
          ),
        })),
      clearTransactions: () => set({ transactions: [] }),
    }),
    {
      name: 'transaction-storage', // Key name in localStorage
      storage: createJSONStorage(() => localStorage),
    },
  ),
);
